enum DataSource {
  SUCCESS,
  NO_CONTENT,
  BAD_REQUEST,
  UNPROCESSABLE_REQUEST,
  FORBIDDEN,
  UNAUTORISED,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  CONNECT_TIMEOUT,
  CANCEL,
  RECIEVE_TIMEOUT,
  SEND_TIMEOUT,
  CACHE_ERROR,
  NO_INTERNET_CONNECTION,
  DEFAULT
}

enum InputType { TEXT, NUMBER, CURRENCY, GOLD_AMOUNT }
